substitutions:
  name: "Syntek-Creations-MultiSensor01"
  friendly_name: "MultiSensor"
  location: "Living Room"
  project_name: ""
  project_version: "0.1"


  temp_offset: "-7"
  humid_offset: "0"


  pir_delay_off: "10s"

esphome:
  name: protopcb-1
  friendly_name: ProtoPCB-1

  esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

logger:

api:

ota:

wifi:

captive_portal:
    
i2c:
     sda: 21
     scl: 22
     scan: true

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature - ${location}"
      filters:
      - offset: $(temp_offset)
    humidity:
      name: "Humidity - ${location}"
      filters:
      - offset: $(humid_offset)
    address: 0x44
    heater_max_duty: 0.0
    update_interval: 20s

  - platform: bh1750
    name: "Illuminance - ${location}"
    address: 0x23
    update_interval: 20s
  
binary_sensor:
  - platform: gpio
    pin:
      number: 32
      mode: INPUT_PULLDOWN
    name: "PIR - ${location}"
    id: pir_motion_sensor
    device_class: motion
    filters:
      - delayed_off: ${pir_delay_off}

light: 
  - platform: status_led
    name: "MS01 Status LED"
    pin: GPIO18

