substitutions:
  name: "syntek-multisensor01"
  friendly_name: "Syntek Creations MS01"
  project_name: "Syntek Creations.MultiSensor (MS01)"
  project_version: "1.0"
  temp_offset: "-7"
  humid_offset: "0"
  pir_delay_off: "10s"
  occupancy_delay_off: "10s"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

improv_serial:

esp32_improv:
  authorizer: none

logger:

api:

ota:

wifi:
  fast_connect: false
  ap: {}

captive_portal:

dashboard_import:
  package_import_url: github://SyntekCreations/MultiSernsor01/multisensor01-ha.yaml@main
  import_full_config: false
    
i2c:
     sda: 21
     scl: 22
     scan: true

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      filters:
        offset: ${temp_offset}
    humidity:
      name: "Humidity"
      filters:
        offset: ${humid_offset}
    address: 0x44
    heater_max_duty: 0.0
    update_interval: 20s

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 20s
  
binary_sensor:
  - platform: gpio
    pin:
      number: 32
      mode: INPUT_PULLDOWN
    name: "PIR Detection"
    id: pirsensor
    device_class: motion
    filters:
      - delayed_off: ${pir_delay_off}

  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLDOWN
    name: "mmWave Detection"
    id: sen0395
    device_class: occupancy

  - platform: template
    name: "Occupancy Combined"
    id: occupancy
    device_class: occupancy
    filters:
      - delayed_off: ${occupancy_delay_off}
    lambda: |-
      if ( id(sen0395).state or id(pirsensor).state) {
        return true;
      } 
      else if (id(sen0395).state == 0 and id(pirsensor).state == 0) {
        return false;
      } 
      else {
        return id(occupancy).state;
      }


light: 
  - platform: status_led
    name: "MS01 Status LED"
    pin: 
      number: 18
    inverted: true
    entity_category: config

