substitutions:
  name: "syntek-creations-multisensor01"
  friendly_name: "MultiSensor"
  room: ""
  project_name: "Syntek Creations.MultiSensor (MS01)"
  project_version: "0.1"
  temp_offset: "-7"
  humid_offset: "0"
  pir_delay_off: "10s"
  occupancy_delay_off: "10s"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  friendly_name: "${friendly_name} - ${location}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

logger:

api:

ota:

wifi:
  ap: {}

captive_portal:
    
i2c:
     sda: 21
     scl: 22
     scan: true

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature - ${location}"
      filters:
        offset: ${temp_offset}
    humidity:
      name: "Humidity - ${location}"
      filters:
        offset: ${humid_offset}
    address: 0x44
    heater_max_duty: 0.0
    update_interval: 20s

  - platform: bh1750
    name: "Illuminance - ${location}"
    address: 0x23
    update_interval: 20s
  
binary_sensor:
  - platform: gpio
    pin:
      number: 32
      mode: INPUT_PULLDOWN
    name: "PIR - ${location}"
    id: pirsensor
    device_class: motion
    filters:
      - delayed_off: ${pir_delay_off}

  - platform: gpio
    name: "mmWave - ${location}"
    id: sen0395
    device_class: occupancy
    pin:
      number: GPIO23
      mode: INPUT_PULLDOWN

  - platform: template
    name: "Occupancy - ${location}"
    id: occupancy
    device_class: occupancy
    filters:
      - delayed_off: ${occupancy_delay_off}
    lambda: |-
      if ( id(sen0395).state or id(pirsensor).state) {
        return true;
      } 
      else if (id(sen0395).state == 0 and id(pirsensor).state == 0) {
        return false;
      } 
      else {
        return id(occupancy).state;
      }


light: 
  - platform: status_led
    name: "MS01 Status LED"
    pin: GPIO18
    entity_category: config

